# Generated by Django 5.0.4 on 2024-05-08 09:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191122_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_phone',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2024, 5, 8, 12, 36, 21, 605644)),
        ),
    ]
